# Generated by Django 4.1.4 on 2022-12-10 05:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150, verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, unique=True, verbose_name='Наименование марки автомобиля')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='AutoCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Объем двигателя (в литрах)')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя (лошадиных сил)')),
                ('gear_shift_box', models.CharField(choices=[('variator', 'Вариатор'), ('mechanical', 'МКПП'), ('auto', 'АКПП')], max_length=150, verbose_name='Тип коробки переключения передач')),
                ('release_year', models.PositiveIntegerField(default='1990', validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nested.auto', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Характеристики автомобиля',
                'verbose_name_plural': 'Характеристики автомобилей',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nested.autobrand', verbose_name='Марка автомобиля'),
        ),
    ]
